"""add flagu attribute to song, album

Revision ID: 10332d47dda7
Revises: 56dc661e82c9
Create Date: 2024-03-13 11:01:44.470369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10332d47dda7'
down_revision = '56dc661e82c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flagu', sa.Boolean(), nullable=True))

    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flagu', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.drop_column('flagu')

    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.drop_column('flagu')

    # ### end Alembic commands ###
