"""foreign keys added

Revision ID: 7fbfd547f052
Revises: 5eb562ba5e85
Create Date: 2024-01-25 10:06:00.756266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fbfd547f052'
down_revision = '5eb562ba5e85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('association', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sid', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pid', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_association_sid', 'songs', ['sid'], ['sid'])
        batch_op.create_foreign_key('fk_association_pid', 'playlists', ['pid'], ['pid'])
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('album_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_songs_album_id', 'albums', ['album_id'], ['a_id'])
        batch_op.create_foreign_key('fk_songs_creator_id', 'users', ['creator_id'], ['uid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('album_id')
        batch_op.drop_column('creator_id')

    with op.batch_alter_table('association', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pid')
        batch_op.drop_column('sid')

    # ### end Alembic commands ###
