"""add largebinary

Revision ID: fe0f8416f582
Revises: 7fbfd547f052
Create Date: 2024-01-29 21:53:44.078516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe0f8416f582'
down_revision = '7fbfd547f052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('song_audio', sa.LargeBinary(), nullable=True))
        batch_op.alter_column('song_cover',
               existing_type=sa.VARCHAR(),
               type_=sa.LargeBinary(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.alter_column('song_cover',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.drop_column('song_audio')

    # ### end Alembic commands ###
